Fix 'source "missing"' error message for Python 3
IOError() generates an OSError in Python 3.6. OSError does not have a
'message' attribute, which caused the following error when trying to add
the hint re. environment variables (the rest of the message was still
displayed):

  AttributeError: 'OSError' object has no attribute 'message'

Use str(exception) instead, which seems to work for both Python 2 and
Python 3.