Give clearer errors for bad endchoice/endif/endmenu nesting
An endchoice/endif/endmenu with no corresponding choice/if/menu
generated a cryptic 'unrecognized construct' parse error. Improve the
error message so that the problem is pointed out explicitly:

  kconfiglib.KconfigError: Kconfig:37: couldn't parse 'endmenu': no corresponding 'menu'

Reported in https://github.com/ulfalizer/Kconfiglib/issues/56.